### ISSUE TITLE
Possible company sources (Reddit)

### ISSUE THREAD

**Issue by thomashoneyman** [ajnsit/purescript-companies#7]
Stumbled across these, which include a few new companies that can be added to the list. I've opened an issue as you might discount them due to age:

- https://www.reddit.com/r/purescript/comments/53r4v7/using_purescript_for_work_sept_16/
- https://www.reddit.com/r/purescript/comments/63n18c/what_are_you_using_purescript_for/
- https://www.reddit.com/r/purescript/comments/3mzotb/using_purescript_for_work/
- https://www.reddit.com/r/purescript/comments/828nex/azara_is_hiring/
- https://www.reddit.com/r/purescript/comments/610quy/hiring_purescript_ui_developers_for_haskell/

There may be more, but this is from a brief search of the PureScript reddit.

**Comment by ajnsit** [comment]
Thanks! I'll look them over.

**Comment by ajnsit** [comment]
I added all of them that I was able to glean some information about. Thanks!
